phases:
- phase: Linux
  queue:
    name: Hosted Linux Preview
    timeoutInMinutes: 5
  steps:
  - script: dotnet build
  - script: dotnet vstest App.Tests1/bin/Debug/netcoreapp2.2/App.Tests1.dll
    timeoutInMinutes: 2
  - script: "ps -ef"
    condition: always()
    displayName: List processes
